name: resikin
description: "Raion Internship Project Aplication"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1 
  google_sign_in: ^6.3.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.2
  smooth_page_indicator: ^1.0.0
  font_awesome_flutter: ^10.0.0
  firebase_storage: ^12.4.4
  cloud_firestore: ^ 5.6.5
  intl: ^0.20.2
  iconsax_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.5
  flutter_svg: ^2.0.17

flutter_native_splash:
  background_image: "assets/images/splash_screen.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/