// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_pxN4qb5l0x6V-Wb6MmvRDf4Hv4LVOLs',
    appId: '1:423243917502:web:fb1541e3f4f203153016ef',
    messagingSenderId: '423243917502',
    projectId: 'resikin-e8b3c',
    authDomain: 'resikin-e8b3c.firebaseapp.com',
    storageBucket: 'resikin-e8b3c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYMFGd-7-oo8TqLsX2akl38wB_X1A9PZ4',
    appId: '1:423243917502:android:53b492e76a9fc5093016ef',
    messagingSenderId: '423243917502',
    projectId: 'resikin-e8b3c',
    storageBucket: 'resikin-e8b3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGt4F4CgKwEcKAnDB0Lq-pKh0Ei7hOaGg',
    appId: '1:423243917502:ios:2f1ac13436318cea3016ef',
    messagingSenderId: '423243917502',
    projectId: 'resikin-e8b3c',
    storageBucket: 'resikin-e8b3c.firebasestorage.app',
    iosBundleId: 'com.example.resikin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGt4F4CgKwEcKAnDB0Lq-pKh0Ei7hOaGg',
    appId: '1:423243917502:ios:2f1ac13436318cea3016ef',
    messagingSenderId: '423243917502',
    projectId: 'resikin-e8b3c',
    storageBucket: 'resikin-e8b3c.firebasestorage.app',
    iosBundleId: 'com.example.resikin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_pxN4qb5l0x6V-Wb6MmvRDf4Hv4LVOLs',
    appId: '1:423243917502:web:4672fb97f12046f63016ef',
    messagingSenderId: '423243917502',
    projectId: 'resikin-e8b3c',
    authDomain: 'resikin-e8b3c.firebaseapp.com',
    storageBucket: 'resikin-e8b3c.firebasestorage.app',
  );
}
